project_id = "mvuuwjnwnijffielncbk"

[functions.handle-order-action]
verify_jwt = false

[functions.request-order-approval]
verify_jwt = false

[functions.request-proof-of-payment]
verify_jwt = false

[functions.admin-orders]
verify_jwt = false

[functions.get-user-orders]
verify_jwt = false
