import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'EN' | 'NL' | 'DE' | 'FR' | 'ES' | 'IT';

export const LANGUAGES: { code: Language; label: string; flag: string }[] = [
  { code: 'EN', label: 'English', flag: '🇬🇧' },
  { code: 'NL', label: 'Nederlands', flag: '🇳🇱' },
  { code: 'DE', label: 'Deutsch', flag: '🇩🇪' },
  { code: 'FR', label: 'Français', flag: '🇫🇷' },
  { code: 'ES', label: 'Español', flag: '🇪🇸' },
  { code: 'IT', label: 'Italiano', flag: '🇮🇹' },
];

// Translation keys
const translations: Record<Language, Record<string, string>> = {
  EN: {
    // Nav
    'nav.men': 'MEN',
    'nav.women': 'WOMEN',
    'nav.shopAll': 'SHOP ALL',
    'nav.contact': 'CONTACT',
    'nav.account': 'ACCOUNT',
    'nav.myAccount': 'MY ACCOUNT',

    // Hero
    'hero.subtitle': 'Premium Fragrances',
    'hero.shopNow': 'Shop Now',
    'hero.instantDelivery': 'Instant Delivery',
    'hero.verifiedSellers': 'Verified Sellers',
    'hero.premiumQuality': 'Premium Quality',

    // Home
    'home.bestsellers': 'Bestsellers',
    'home.bestsellersDesc': 'Our most loved fragrances',
    'home.viewAll': 'View All',
    'home.bundles': 'Fragrance Bundles',
    'home.bundlesDesc': 'Save more with curated bundles',
    'home.faq': 'Frequently Asked Questions',
    'home.faqDesc': 'Everything you need to know',
    'home.shopByBrand': 'Shop by Brand',

    // FAQ
    'faq.q1': 'What am I buying?',
    'faq.a1': 'You are purchasing access to exclusive fragrance seller links from our verified partners.',
    'faq.q2': 'How do I receive my purchase?',
    'faq.a2': 'After completing your order, you will receive your purchase via email instantly. Digital delivery is immediate.',
    'faq.q3': "What's your refund policy?",
    'faq.a3': 'Due to the digital nature of our products, all sales are final. No refunds or exchanges are available once seller links have been delivered.',
    'faq.q4': 'What kind of fragrances do you sell?',
    'faq.a4': 'We offer high-quality 1:1 inspired fragrances sourced from trusted sellers. These are not original brand products.',
    'faq.q5': 'How do I contact the sellers?',
    'faq.a5': "After purchase, you'll receive the seller link via email with all necessary contact information.",

    // Shop
    'shop.title': 'Shop',
    'shop.menCollection': "Men's Collection",
    'shop.womenCollection': "Women's Collection",
    'shop.allProducts': 'All Products',
    'shop.searchPlaceholder': 'Search fragrances...',
    'shop.sortBy': 'Sort by',
    'shop.featured': 'Featured',
    'shop.priceLowHigh': 'Price: Low to High',
    'shop.priceHighLow': 'Price: High to Low',
    'shop.newest': 'Newest',
    'shop.filters': 'Filters',
    'shop.priceRange': 'Price Range',
    'shop.brands': 'Brands',
    'shop.noProducts': 'No products found',
    'shop.clearFilters': 'Clear filters',
    'shop.products': 'products',

    // Product Card
    'product.addToCart': 'Add to Cart',
    'product.viewDetails': 'View Details',
    'product.off': 'OFF',
    'product.from': 'From',

    // Checkout
    'checkout.title': 'Checkout',
    'checkout.subtitle': 'Complete your purchase',
    'checkout.yourInfo': 'Your Information',
    'checkout.email': 'EMAIL ADDRESS',
    'checkout.emailPlaceholder': 'your@email.com',
    'checkout.emailHelper': 'Please make sure your email is correct to ensure you get the order confirmation email correctly.',
    'checkout.firstName': 'FIRST NAME',
    'checkout.lastName': 'LAST NAME',
    'checkout.country': 'COUNTRY',
    'checkout.selectCountry': 'Select country...',
    'checkout.searchCountry': 'Search country...',
    'checkout.noCountry': 'No country found.',
    'checkout.city': 'CITY',
    'checkout.postalCode': 'POSTAL CODE',
    'checkout.streetAddress': 'STREET ADDRESS',
    'checkout.discountCode': 'DISCOUNT CODE',
    'checkout.applyDiscount': 'Apply',
    'checkout.discountApplied': 'applied',
    'checkout.orderSummary': 'Order Summary',
    'checkout.subtotal': 'Subtotal',
    'checkout.discount': 'Discount',
    'checkout.total': 'Total',
    'checkout.payment': 'Payment',
    'checkout.payWithCard': 'Pay with Card/Apple Pay',
    'checkout.payWithGiftCard': 'Pay with gift card',
    'checkout.giftCardOther': 'If the other payment methods don\'t work for you',
    'checkout.giftCardCode': 'GIFT CARD CODE',
    'checkout.giftCardPlaceholder': 'Enter your gift card code',
    'checkout.confirmPayment': 'Confirm Payment',
    'checkout.confirmOrder': "I've Completed Payment — Confirm Order",
    'checkout.processing': 'Processing...',
    'checkout.emptyCart': 'Your cart is empty',
    'checkout.emptyCartDesc': 'Add some items to your cart to proceed with checkout.',
    'checkout.continueShopping': 'Continue Shopping',
    'checkout.fillFields': 'Please fill in all fields',
    'checkout.fillFieldsDesc': 'Complete your shipping information before paying.',

    // Revolut popup
    'checkout.revolutPopupTitle': 'Important Payment Instructions',
    'checkout.revolutPopupText1': 'You must enter exactly',
    'checkout.revolutPopupText2': 'at the payment link. Orders with incorrect amounts will',
    'checkout.revolutPopupText3': 'not',
    'checkout.revolutPopupText4': 'be accepted.',
    'checkout.revolutPopupText5': 'After completing your payment, please come back to this window to confirm your payment.',
    'checkout.revolutPopupCancel': 'Cancel',
    'checkout.revolutPopupAccept': 'I Understand, Proceed to Payment',

    // Confirm dialog
    'checkout.confirmTitle': 'Payment Confirmation',
    'checkout.confirmWarning': 'Orders confirmed without payment will be rejected upon review.',
    'checkout.confirmText': 'Your order will be reviewed before a confirmation email is sent. If payment has not been completed, your order will be rejected. Are you sure you have completed the payment?',
    'checkout.confirmGoBack': 'Go Back',
    'checkout.confirmYes': "Yes, I've Paid",
    'checkout.rejectedWarning': 'Orders confirmed without payment will be rejected upon review.',

    // Gift card popup
    'checkout.giftCardPopupTitle': 'Gift Card Payment',
    'checkout.giftCardPopupText': 'If the other payment options do not work for you, purchase a gift card from this link that is closest to your order amount, and once you\'re done, come back to the site. There will be a space for you to enter the code you purchased. Once it\'s been pasted then click confirm payment and your order will be processed.',
    'checkout.giftCardPopupCancel': 'Cancel',
    'checkout.giftCardPopupAccept': 'Go to Gift Card Site',

    // Gift card confirm dialog
    'checkout.giftCardConfirmTitle': 'Confirm Gift Card Payment',
    'checkout.giftCardConfirmText': 'Are you sure you want to submit this gift card code? Your order will be reviewed and you will receive a confirmation email once the code is verified.',
    'checkout.giftCardConfirmGoBack': 'Go Back',
    'checkout.giftCardConfirmYes': 'Submit Gift Card Code',

    // Thank you
    'checkout.thankYou': 'Thank You!',
    'checkout.thankYouPaypal': 'Your purchase is complete. You will receive an email with your order details.',
    'checkout.thankYouRevolut': 'Your order has been received. You will get the order confirmation email as soon as payment is verified.',
    'checkout.thankYouGiftCard': 'Your order has been received. You will receive the order confirmation email as soon as the code is verified.',
    'checkout.thankYouSpam': "Please check your spam folder if you don't see it within a few minutes.",
    'checkout.thankYouPatience': 'This usually takes a short while. Thank you for your patience.',

    // Footer
    'footer.description': 'Discover exclusive fragrance seller links. Premium quality, instant digital delivery.',
    'footer.shop': 'Shop',
    'footer.menCollection': "Men's Collection",
    'footer.womenCollection': "Women's Collection",
    'footer.allProducts': 'All Products',
    'footer.support': 'Support',
    'footer.contactUs': 'Contact Us',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',
    'footer.faq': 'FAQ',
    'footer.rights': 'All rights reserved.',

    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': "We'd love to hear from you",

    // Product Detail
    'productDetail.scentNotes': 'Scent Notes',
    'productDetail.reviews': 'Reviews',
    'productDetail.delivery': 'Delivery',

    // Cart
    'cart.title': 'Your Cart',
    'cart.empty': 'Your cart is empty',
    'cart.checkout': 'Checkout',
    'cart.remove': 'Remove',

    // Auth
    'auth.login': 'Sign In',
    'auth.signup': 'Sign Up',
    'auth.logout': 'Sign Out',

    // General
    'general.poweredBy': 'Powered by Revolut',
    'general.secure': 'Secure',
    'general.or': 'or',
    'general.information': 'Information',
    'general.confirmation': 'Confirmation',
    'general.step': 'Step',
  },

  NL: {
    'nav.men': 'HEREN',
    'nav.women': 'DAMES',
    'nav.shopAll': 'ALLES',
    'nav.contact': 'CONTACT',
    'nav.account': 'ACCOUNT',
    'nav.myAccount': 'MIJN ACCOUNT',
    'hero.subtitle': 'Premium Parfums',
    'hero.shopNow': 'Nu Winkelen',
    'hero.instantDelivery': 'Directe Levering',
    'hero.verifiedSellers': 'Geverifieerde Verkopers',
    'hero.premiumQuality': 'Premium Kwaliteit',
    'home.bestsellers': 'Bestsellers',
    'home.bestsellersDesc': 'Onze meest geliefde geuren',
    'home.viewAll': 'Bekijk Alles',
    'home.bundles': 'Geurenbundels',
    'home.bundlesDesc': 'Bespaar meer met samengestelde bundels',
    'home.faq': 'Veelgestelde Vragen',
    'home.faqDesc': 'Alles wat je moet weten',
    'home.shopByBrand': 'Shop per Merk',
    'faq.q1': 'Wat koop ik?',
    'faq.a1': 'Je koopt toegang tot exclusieve verkooplinks van onze geverifieerde partners.',
    'faq.q2': 'Hoe ontvang ik mijn aankoop?',
    'faq.a2': 'Na het voltooien van je bestelling ontvang je je aankoop direct per e-mail.',
    'faq.q3': 'Wat is jullie retourbeleid?',
    'faq.a3': 'Vanwege de digitale aard van onze producten zijn alle verkopen definitief. Geen restitutie of omruiling mogelijk.',
    'faq.q4': 'Wat voor soort parfums verkopen jullie?',
    'faq.a4': 'Wij bieden hoogwaardige 1:1 geïnspireerde parfums van vertrouwde verkopers. Dit zijn geen originele merkproducten.',
    'faq.q5': 'Hoe neem ik contact op met de verkopers?',
    'faq.a5': 'Na aankoop ontvang je de verkooplink per e-mail met alle benodigde contactinformatie.',
    'shop.title': 'Winkel',
    'shop.menCollection': 'Herencollectie',
    'shop.womenCollection': 'Damescollectie',
    'shop.allProducts': 'Alle Producten',
    'shop.searchPlaceholder': 'Zoek parfums...',
    'shop.sortBy': 'Sorteer op',
    'shop.featured': 'Uitgelicht',
    'shop.priceLowHigh': 'Prijs: Laag naar Hoog',
    'shop.priceHighLow': 'Prijs: Hoog naar Laag',
    'shop.newest': 'Nieuwste',
    'shop.filters': 'Filters',
    'shop.priceRange': 'Prijsbereik',
    'shop.brands': 'Merken',
    'shop.noProducts': 'Geen producten gevonden',
    'shop.clearFilters': 'Filters wissen',
    'shop.products': 'producten',
    'product.addToCart': 'In Winkelwagen',
    'product.viewDetails': 'Details Bekijken',
    'product.off': 'KORTING',
    'product.from': 'Vanaf',
    'checkout.title': 'Afrekenen',
    'checkout.subtitle': 'Voltooi je aankoop',
    'checkout.yourInfo': 'Jouw Gegevens',
    'checkout.email': 'E-MAILADRES',
    'checkout.emailPlaceholder': 'jouw@email.com',
    'checkout.emailHelper': 'Zorg ervoor dat je e-mailadres correct is zodat je de bevestigingsmail ontvangt.',
    'checkout.firstName': 'VOORNAAM',
    'checkout.lastName': 'ACHTERNAAM',
    'checkout.country': 'LAND',
    'checkout.selectCountry': 'Selecteer land...',
    'checkout.searchCountry': 'Zoek land...',
    'checkout.noCountry': 'Geen land gevonden.',
    'checkout.city': 'STAD',
    'checkout.postalCode': 'POSTCODE',
    'checkout.streetAddress': 'STRAATNAAM',
    'checkout.discountCode': 'KORTINGSCODE',
    'checkout.applyDiscount': 'Toepassen',
    'checkout.discountApplied': 'toegepast',
    'checkout.orderSummary': 'Besteloverzicht',
    'checkout.subtotal': 'Subtotaal',
    'checkout.discount': 'Korting',
    'checkout.total': 'Totaal',
    'checkout.payment': 'Betaling',
    'checkout.payWithCard': 'Betaal met Kaart/Apple Pay',
    'checkout.payWithGiftCard': 'Betaal met cadeaukaart',
    'checkout.giftCardOther': 'Als de andere betaalmethoden niet werken',
    'checkout.giftCardCode': 'CADEAUKAARTCODE',
    'checkout.giftCardPlaceholder': 'Voer je cadeaukaartcode in',
    'checkout.confirmPayment': 'Betaling Bevestigen',
    'checkout.confirmOrder': 'Ik heb betaald — Bestelling Bevestigen',
    'checkout.processing': 'Verwerken...',
    'checkout.emptyCart': 'Je winkelwagen is leeg',
    'checkout.emptyCartDesc': 'Voeg items toe aan je winkelwagen om af te rekenen.',
    'checkout.continueShopping': 'Verder Winkelen',
    'checkout.fillFields': 'Vul alle velden in',
    'checkout.fillFieldsDesc': 'Vul je gegevens in voordat je betaalt.',
    'checkout.revolutPopupTitle': 'Belangrijke Betalingsinstructies',
    'checkout.revolutPopupText1': 'Je moet exact',
    'checkout.revolutPopupText2': 'invoeren bij de betalingslink. Bestellingen met onjuiste bedragen worden',
    'checkout.revolutPopupText3': 'niet',
    'checkout.revolutPopupText4': 'geaccepteerd.',
    'checkout.revolutPopupText5': 'Kom na het voltooien van je betaling terug naar dit venster om je betaling te bevestigen.',
    'checkout.revolutPopupCancel': 'Annuleren',
    'checkout.revolutPopupAccept': 'Ik Begrijp Het, Ga naar Betaling',
    'checkout.confirmTitle': 'Betalingsbevestiging',
    'checkout.confirmWarning': 'Bestellingen zonder betaling worden bij controle afgewezen.',
    'checkout.confirmText': 'Je bestelling wordt beoordeeld voordat een bevestigingsmail wordt verzonden. Als de betaling niet is voltooid, wordt je bestelling afgewezen. Weet je zeker dat je hebt betaald?',
    'checkout.confirmGoBack': 'Terug',
    'checkout.confirmYes': 'Ja, Ik Heb Betaald',
    'checkout.rejectedWarning': 'Bestellingen zonder betaling worden bij controle afgewezen.',
    'checkout.giftCardPopupTitle': 'Cadeaukaart Betaling',
    'checkout.giftCardPopupText': 'Als de andere betaalopties niet voor je werken, koop dan een cadeaukaart via deze link die het dichtst bij je bestelbedrag ligt. Kom daarna terug naar de site en voer de code in. Klik vervolgens op betaling bevestigen.',
    'checkout.giftCardPopupCancel': 'Annuleren',
    'checkout.giftCardPopupAccept': 'Ga naar Cadeaukaart Site',
    'checkout.giftCardConfirmTitle': 'Cadeaukaart Betaling Bevestigen',
    'checkout.giftCardConfirmText': 'Weet je zeker dat je deze cadeaukaartcode wilt indienen? Je bestelling wordt beoordeeld en je ontvangt een bevestigingsmail zodra de code is geverifieerd.',
    'checkout.giftCardConfirmGoBack': 'Terug',
    'checkout.giftCardConfirmYes': 'Cadeaukaartcode Indienen',
    'checkout.thankYou': 'Bedankt!',
    'checkout.thankYouPaypal': 'Je aankoop is voltooid. Je ontvangt een e-mail met je bestelgegevens.',
    'checkout.thankYouRevolut': 'Je bestelling is ontvangen. Je ontvangt de bevestigingsmail zodra de betaling is geverifieerd.',
    'checkout.thankYouGiftCard': 'Je bestelling is ontvangen. Je ontvangt de bevestigingsmail zodra de code is geverifieerd.',
    'checkout.thankYouSpam': 'Controleer je spammap als je de e-mail niet binnen enkele minuten ontvangt.',
    'checkout.thankYouPatience': 'Dit duurt meestal even. Bedankt voor je geduld.',
    'footer.description': 'Ontdek exclusieve parfumverkooplinks. Premium kwaliteit, directe digitale levering.',
    'footer.shop': 'Winkel',
    'footer.menCollection': 'Herencollectie',
    'footer.womenCollection': 'Damescollectie',
    'footer.allProducts': 'Alle Producten',
    'footer.support': 'Ondersteuning',
    'footer.contactUs': 'Neem Contact Op',
    'footer.privacyPolicy': 'Privacybeleid',
    'footer.termsOfService': 'Servicevoorwaarden',
    'footer.faq': 'FAQ',
    'footer.rights': 'Alle rechten voorbehouden.',
    'contact.title': 'Neem Contact Op',
    'contact.subtitle': 'We horen graag van je',
    'productDetail.scentNotes': 'Geurnotities',
    'productDetail.reviews': 'Beoordelingen',
    'productDetail.delivery': 'Levering',
    'cart.title': 'Je Winkelwagen',
    'cart.empty': 'Je winkelwagen is leeg',
    'cart.checkout': 'Afrekenen',
    'cart.remove': 'Verwijderen',
    'auth.login': 'Inloggen',
    'auth.signup': 'Registreren',
    'auth.logout': 'Uitloggen',
    'general.poweredBy': 'Mogelijk gemaakt door Revolut',
    'general.secure': 'Beveiligd',
    'general.or': 'of',
    'general.information': 'Informatie',
    'general.confirmation': 'Bevestiging',
    'general.step': 'Stap',
  },

  DE: {
    'nav.men': 'HERREN',
    'nav.women': 'DAMEN',
    'nav.shopAll': 'ALLE',
    'nav.contact': 'KONTAKT',
    'nav.account': 'KONTO',
    'nav.myAccount': 'MEIN KONTO',
    'hero.subtitle': 'Premium Düfte',
    'hero.shopNow': 'Jetzt Einkaufen',
    'hero.instantDelivery': 'Sofortige Lieferung',
    'hero.verifiedSellers': 'Verifizierte Verkäufer',
    'hero.premiumQuality': 'Premium Qualität',
    'home.bestsellers': 'Bestseller',
    'home.bestsellersDesc': 'Unsere beliebtesten Düfte',
    'home.viewAll': 'Alle Anzeigen',
    'home.bundles': 'Duft-Bundles',
    'home.bundlesDesc': 'Mehr sparen mit kuratierten Bundles',
    'home.faq': 'Häufig Gestellte Fragen',
    'home.faqDesc': 'Alles was du wissen musst',
    'home.shopByBrand': 'Nach Marke Einkaufen',
    'faq.q1': 'Was kaufe ich?',
    'faq.a1': 'Du kaufst Zugang zu exklusiven Verkäuferlinks unserer verifizierten Partner.',
    'faq.q2': 'Wie erhalte ich meinen Kauf?',
    'faq.a2': 'Nach Abschluss deiner Bestellung erhältst du deinen Kauf sofort per E-Mail.',
    'faq.q3': 'Was ist eure Rückgaberichtlinie?',
    'faq.a3': 'Aufgrund der digitalen Natur unserer Produkte sind alle Verkäufe endgültig. Keine Rückerstattungen oder Umtausch möglich.',
    'faq.q4': 'Was für Düfte verkauft ihr?',
    'faq.a4': 'Wir bieten hochwertige 1:1 inspirierte Düfte von vertrauenswürdigen Verkäufern. Dies sind keine Originalmarkenprodukte.',
    'faq.q5': 'Wie kontaktiere ich die Verkäufer?',
    'faq.a5': 'Nach dem Kauf erhältst du den Verkäuferlink per E-Mail mit allen nötigen Kontaktinformationen.',
    'shop.title': 'Shop',
    'shop.menCollection': 'Herrenkollektion',
    'shop.womenCollection': 'Damenkollektion',
    'shop.allProducts': 'Alle Produkte',
    'shop.searchPlaceholder': 'Düfte suchen...',
    'shop.sortBy': 'Sortieren nach',
    'shop.featured': 'Empfohlen',
    'shop.priceLowHigh': 'Preis: Niedrig bis Hoch',
    'shop.priceHighLow': 'Preis: Hoch bis Niedrig',
    'shop.newest': 'Neueste',
    'shop.filters': 'Filter',
    'shop.priceRange': 'Preisbereich',
    'shop.brands': 'Marken',
    'shop.noProducts': 'Keine Produkte gefunden',
    'shop.clearFilters': 'Filter löschen',
    'shop.products': 'Produkte',
    'product.addToCart': 'In den Warenkorb',
    'product.viewDetails': 'Details Ansehen',
    'product.off': 'RABATT',
    'product.from': 'Ab',
    'checkout.title': 'Kasse',
    'checkout.subtitle': 'Schließe deinen Einkauf ab',
    'checkout.yourInfo': 'Deine Informationen',
    'checkout.email': 'E-MAIL-ADRESSE',
    'checkout.emailPlaceholder': 'deine@email.com',
    'checkout.emailHelper': 'Stelle sicher, dass deine E-Mail korrekt ist, damit du die Bestellbestätigung erhältst.',
    'checkout.firstName': 'VORNAME',
    'checkout.lastName': 'NACHNAME',
    'checkout.country': 'LAND',
    'checkout.selectCountry': 'Land auswählen...',
    'checkout.searchCountry': 'Land suchen...',
    'checkout.noCountry': 'Kein Land gefunden.',
    'checkout.city': 'STADT',
    'checkout.postalCode': 'POSTLEITZAHL',
    'checkout.streetAddress': 'STRASSE',
    'checkout.discountCode': 'RABATTCODE',
    'checkout.applyDiscount': 'Anwenden',
    'checkout.discountApplied': 'angewendet',
    'checkout.orderSummary': 'Bestellübersicht',
    'checkout.subtotal': 'Zwischensumme',
    'checkout.discount': 'Rabatt',
    'checkout.total': 'Gesamt',
    'checkout.payment': 'Zahlung',
    'checkout.payWithCard': 'Mit Karte/Apple Pay bezahlen',
    'checkout.payWithGiftCard': 'Mit Geschenkkarte bezahlen',
    'checkout.giftCardOther': 'Wenn die anderen Zahlungsmethoden nicht funktionieren',
    'checkout.giftCardCode': 'GESCHENKKARTENCODE',
    'checkout.giftCardPlaceholder': 'Geschenkkartencode eingeben',
    'checkout.confirmPayment': 'Zahlung Bestätigen',
    'checkout.confirmOrder': 'Ich habe bezahlt — Bestellung Bestätigen',
    'checkout.processing': 'Wird verarbeitet...',
    'checkout.emptyCart': 'Dein Warenkorb ist leer',
    'checkout.emptyCartDesc': 'Füge Artikel zu deinem Warenkorb hinzu, um zur Kasse zu gehen.',
    'checkout.continueShopping': 'Weiter Einkaufen',
    'checkout.fillFields': 'Bitte fülle alle Felder aus',
    'checkout.fillFieldsDesc': 'Vervollständige deine Informationen vor der Zahlung.',
    'checkout.revolutPopupTitle': 'Wichtige Zahlungshinweise',
    'checkout.revolutPopupText1': 'Du musst genau',
    'checkout.revolutPopupText2': 'beim Zahlungslink eingeben. Bestellungen mit falschen Beträgen werden',
    'checkout.revolutPopupText3': 'nicht',
    'checkout.revolutPopupText4': 'akzeptiert.',
    'checkout.revolutPopupText5': 'Komm nach Abschluss der Zahlung zu diesem Fenster zurück, um deine Zahlung zu bestätigen.',
    'checkout.revolutPopupCancel': 'Abbrechen',
    'checkout.revolutPopupAccept': 'Verstanden, Weiter zur Zahlung',
    'checkout.confirmTitle': 'Zahlungsbestätigung',
    'checkout.confirmWarning': 'Bestellungen ohne Zahlung werden bei der Überprüfung abgelehnt.',
    'checkout.confirmText': 'Deine Bestellung wird überprüft, bevor eine Bestätigungsmail gesendet wird. Wenn die Zahlung nicht abgeschlossen wurde, wird deine Bestellung abgelehnt. Bist du sicher, dass du bezahlt hast?',
    'checkout.confirmGoBack': 'Zurück',
    'checkout.confirmYes': 'Ja, Ich Habe Bezahlt',
    'checkout.rejectedWarning': 'Bestellungen ohne Zahlung werden bei der Überprüfung abgelehnt.',
    'checkout.giftCardPopupTitle': 'Geschenkkarten-Zahlung',
    'checkout.giftCardPopupText': 'Wenn die anderen Zahlungsoptionen nicht funktionieren, kaufe eine Geschenkkarte über diesen Link, die deinem Bestellbetrag am nächsten kommt. Komm dann zurück und gib den Code ein. Klicke dann auf Zahlung bestätigen.',
    'checkout.giftCardPopupCancel': 'Abbrechen',
    'checkout.giftCardPopupAccept': 'Zur Geschenkkarten-Seite',
    'checkout.giftCardConfirmTitle': 'Geschenkkarten-Zahlung Bestätigen',
    'checkout.giftCardConfirmText': 'Bist du sicher, dass du diesen Geschenkkartencode einreichen möchtest? Deine Bestellung wird überprüft und du erhältst eine Bestätigungsmail, sobald der Code verifiziert ist.',
    'checkout.giftCardConfirmGoBack': 'Zurück',
    'checkout.giftCardConfirmYes': 'Geschenkkartencode Einreichen',
    'checkout.thankYou': 'Vielen Dank!',
    'checkout.thankYouPaypal': 'Dein Kauf ist abgeschlossen. Du erhältst eine E-Mail mit deinen Bestelldetails.',
    'checkout.thankYouRevolut': 'Deine Bestellung wurde empfangen. Du erhältst die Bestätigungsmail, sobald die Zahlung verifiziert ist.',
    'checkout.thankYouGiftCard': 'Deine Bestellung wurde empfangen. Du erhältst die Bestätigungsmail, sobald der Code verifiziert ist.',
    'checkout.thankYouSpam': 'Überprüfe deinen Spam-Ordner, falls du die E-Mail nicht innerhalb weniger Minuten erhältst.',
    'checkout.thankYouPatience': 'Dies dauert normalerweise einen kurzen Moment. Vielen Dank für deine Geduld.',
    'footer.description': 'Entdecke exklusive Parfüm-Verkäuferlinks. Premium Qualität, sofortige digitale Lieferung.',
    'footer.shop': 'Shop',
    'footer.menCollection': 'Herrenkollektion',
    'footer.womenCollection': 'Damenkollektion',
    'footer.allProducts': 'Alle Produkte',
    'footer.support': 'Support',
    'footer.contactUs': 'Kontakt',
    'footer.privacyPolicy': 'Datenschutz',
    'footer.termsOfService': 'AGB',
    'footer.faq': 'FAQ',
    'footer.rights': 'Alle Rechte vorbehalten.',
    'contact.title': 'Kontakt',
    'contact.subtitle': 'Wir freuen uns von dir zu hören',
    'productDetail.scentNotes': 'Duftnoten',
    'productDetail.reviews': 'Bewertungen',
    'productDetail.delivery': 'Lieferung',
    'cart.title': 'Dein Warenkorb',
    'cart.empty': 'Dein Warenkorb ist leer',
    'cart.checkout': 'Zur Kasse',
    'cart.remove': 'Entfernen',
    'auth.login': 'Anmelden',
    'auth.signup': 'Registrieren',
    'auth.logout': 'Abmelden',
    'general.poweredBy': 'Powered by Revolut',
    'general.secure': 'Sicher',
    'general.or': 'oder',
    'general.information': 'Information',
    'general.confirmation': 'Bestätigung',
    'general.step': 'Schritt',
  },

  FR: {
    'nav.men': 'HOMME',
    'nav.women': 'FEMME',
    'nav.shopAll': 'TOUT',
    'nav.contact': 'CONTACT',
    'nav.account': 'COMPTE',
    'nav.myAccount': 'MON COMPTE',
    'hero.subtitle': 'Parfums Premium',
    'hero.shopNow': 'Acheter',
    'hero.instantDelivery': 'Livraison Instantanée',
    'hero.verifiedSellers': 'Vendeurs Vérifiés',
    'hero.premiumQuality': 'Qualité Premium',
    'home.bestsellers': 'Meilleures Ventes',
    'home.bestsellersDesc': 'Nos parfums les plus appréciés',
    'home.viewAll': 'Voir Tout',
    'home.bundles': 'Coffrets Parfums',
    'home.bundlesDesc': 'Économisez avec nos coffrets',
    'home.faq': 'Questions Fréquentes',
    'home.faqDesc': 'Tout ce que vous devez savoir',
    'home.shopByBrand': 'Par Marque',
    'faq.q1': "Qu'est-ce que j'achète ?",
    'faq.a1': "Vous achetez l'accès à des liens vendeurs exclusifs de nos partenaires vérifiés.",
    'faq.q2': 'Comment recevrai-je mon achat ?',
    'faq.a2': 'Après votre commande, vous recevrez votre achat par e-mail instantanément.',
    'faq.q3': 'Quelle est votre politique de remboursement ?',
    'faq.a3': 'En raison de la nature numérique de nos produits, toutes les ventes sont définitives.',
    'faq.q4': 'Quel type de parfums vendez-vous ?',
    'faq.a4': 'Nous proposons des parfums 1:1 de haute qualité provenant de vendeurs de confiance. Ce ne sont pas des produits de marque originaux.',
    'faq.q5': 'Comment contacter les vendeurs ?',
    'faq.a5': "Après l'achat, vous recevrez le lien vendeur par e-mail avec toutes les informations de contact.",
    'shop.title': 'Boutique',
    'shop.menCollection': 'Collection Homme',
    'shop.womenCollection': 'Collection Femme',
    'shop.allProducts': 'Tous les Produits',
    'shop.searchPlaceholder': 'Rechercher des parfums...',
    'shop.sortBy': 'Trier par',
    'shop.featured': 'En Vedette',
    'shop.priceLowHigh': 'Prix: Croissant',
    'shop.priceHighLow': 'Prix: Décroissant',
    'shop.newest': 'Nouveautés',
    'shop.filters': 'Filtres',
    'shop.priceRange': 'Fourchette de Prix',
    'shop.brands': 'Marques',
    'shop.noProducts': 'Aucun produit trouvé',
    'shop.clearFilters': 'Effacer les filtres',
    'shop.products': 'produits',
    'product.addToCart': 'Ajouter au Panier',
    'product.viewDetails': 'Voir les Détails',
    'product.off': 'RÉDUCTION',
    'product.from': 'À partir de',
    'checkout.title': 'Paiement',
    'checkout.subtitle': 'Finalisez votre achat',
    'checkout.yourInfo': 'Vos Informations',
    'checkout.email': 'ADRESSE E-MAIL',
    'checkout.emailPlaceholder': 'votre@email.com',
    'checkout.emailHelper': "Assurez-vous que votre e-mail est correct pour recevoir l'e-mail de confirmation.",
    'checkout.firstName': 'PRÉNOM',
    'checkout.lastName': 'NOM',
    'checkout.country': 'PAYS',
    'checkout.selectCountry': 'Sélectionner un pays...',
    'checkout.searchCountry': 'Rechercher un pays...',
    'checkout.noCountry': 'Aucun pays trouvé.',
    'checkout.city': 'VILLE',
    'checkout.postalCode': 'CODE POSTAL',
    'checkout.streetAddress': 'ADRESSE',
    'checkout.discountCode': 'CODE PROMO',
    'checkout.applyDiscount': 'Appliquer',
    'checkout.discountApplied': 'appliqué',
    'checkout.orderSummary': 'Résumé de Commande',
    'checkout.subtotal': 'Sous-total',
    'checkout.discount': 'Réduction',
    'checkout.total': 'Total',
    'checkout.payment': 'Paiement',
    'checkout.payWithCard': 'Payer par Carte/Apple Pay',
    'checkout.payWithGiftCard': 'Payer par carte cadeau',
    'checkout.giftCardOther': "Si les autres méthodes de paiement ne fonctionnent pas",
    'checkout.giftCardCode': 'CODE CARTE CADEAU',
    'checkout.giftCardPlaceholder': 'Entrez votre code carte cadeau',
    'checkout.confirmPayment': 'Confirmer le Paiement',
    'checkout.confirmOrder': "J'ai payé — Confirmer la Commande",
    'checkout.processing': 'Traitement...',
    'checkout.emptyCart': 'Votre panier est vide',
    'checkout.emptyCartDesc': 'Ajoutez des articles à votre panier pour passer à la caisse.',
    'checkout.continueShopping': 'Continuer vos Achats',
    'checkout.fillFields': 'Veuillez remplir tous les champs',
    'checkout.fillFieldsDesc': 'Complétez vos informations avant de payer.',
    'checkout.revolutPopupTitle': 'Instructions de Paiement Importantes',
    'checkout.revolutPopupText1': 'Vous devez entrer exactement',
    'checkout.revolutPopupText2': 'sur le lien de paiement. Les commandes avec des montants incorrects ne seront',
    'checkout.revolutPopupText3': 'pas',
    'checkout.revolutPopupText4': 'acceptées.',
    'checkout.revolutPopupText5': 'Après avoir effectué votre paiement, revenez à cette fenêtre pour confirmer votre paiement.',
    'checkout.revolutPopupCancel': 'Annuler',
    'checkout.revolutPopupAccept': "J'ai Compris, Procéder au Paiement",
    'checkout.confirmTitle': 'Confirmation de Paiement',
    'checkout.confirmWarning': 'Les commandes sans paiement seront rejetées lors de la vérification.',
    'checkout.confirmText': "Votre commande sera examinée avant l'envoi d'un e-mail de confirmation. Si le paiement n'a pas été effectué, votre commande sera rejetée. Êtes-vous sûr d'avoir payé ?",
    'checkout.confirmGoBack': 'Retour',
    'checkout.confirmYes': "Oui, J'ai Payé",
    'checkout.rejectedWarning': 'Les commandes sans paiement seront rejetées lors de la vérification.',
    'checkout.giftCardPopupTitle': 'Paiement par Carte Cadeau',
    'checkout.giftCardPopupText': "Si les autres options de paiement ne fonctionnent pas, achetez une carte cadeau via ce lien au montant le plus proche de votre commande. Revenez ensuite sur le site et entrez le code. Cliquez ensuite sur confirmer le paiement.",
    'checkout.giftCardPopupCancel': 'Annuler',
    'checkout.giftCardPopupAccept': 'Aller au Site de Cartes Cadeaux',
    'checkout.giftCardConfirmTitle': 'Confirmer le Paiement par Carte Cadeau',
    'checkout.giftCardConfirmText': "Êtes-vous sûr de vouloir soumettre ce code carte cadeau ? Votre commande sera examinée et vous recevrez un e-mail de confirmation une fois le code vérifié.",
    'checkout.giftCardConfirmGoBack': 'Retour',
    'checkout.giftCardConfirmYes': 'Soumettre le Code Carte Cadeau',
    'checkout.thankYou': 'Merci !',
    'checkout.thankYouPaypal': 'Votre achat est terminé. Vous recevrez un e-mail avec les détails de votre commande.',
    'checkout.thankYouRevolut': 'Votre commande a été reçue. Vous recevrez un e-mail de confirmation dès que le paiement sera vérifié.',
    'checkout.thankYouGiftCard': 'Votre commande a été reçue. Vous recevrez un e-mail de confirmation dès que le code sera vérifié.',
    'checkout.thankYouSpam': "Vérifiez votre dossier spam si vous ne recevez pas l'e-mail dans les prochaines minutes.",
    'checkout.thankYouPatience': 'Cela prend généralement un court moment. Merci de votre patience.',
    'footer.description': 'Découvrez des liens vendeurs exclusifs de parfums. Qualité premium, livraison numérique instantanée.',
    'footer.shop': 'Boutique',
    'footer.menCollection': 'Collection Homme',
    'footer.womenCollection': 'Collection Femme',
    'footer.allProducts': 'Tous les Produits',
    'footer.support': 'Support',
    'footer.contactUs': 'Contactez-nous',
    'footer.privacyPolicy': 'Confidentialité',
    'footer.termsOfService': 'CGV',
    'footer.faq': 'FAQ',
    'footer.rights': 'Tous droits réservés.',
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Nous serions ravis de vous entendre',
    'productDetail.scentNotes': 'Notes Olfactives',
    'productDetail.reviews': 'Avis',
    'productDetail.delivery': 'Livraison',
    'cart.title': 'Votre Panier',
    'cart.empty': 'Votre panier est vide',
    'cart.checkout': 'Payer',
    'cart.remove': 'Supprimer',
    'auth.login': 'Connexion',
    'auth.signup': 'Inscription',
    'auth.logout': 'Déconnexion',
    'general.poweredBy': 'Propulsé par Revolut',
    'general.secure': 'Sécurisé',
    'general.or': 'ou',
    'general.information': 'Information',
    'general.confirmation': 'Confirmation',
    'general.step': 'Étape',
  },

  ES: {
    'nav.men': 'HOMBRE',
    'nav.women': 'MUJER',
    'nav.shopAll': 'TODO',
    'nav.contact': 'CONTACTO',
    'nav.account': 'CUENTA',
    'nav.myAccount': 'MI CUENTA',
    'hero.subtitle': 'Fragancias Premium',
    'hero.shopNow': 'Comprar Ahora',
    'hero.instantDelivery': 'Entrega Instantánea',
    'hero.verifiedSellers': 'Vendedores Verificados',
    'hero.premiumQuality': 'Calidad Premium',
    'home.bestsellers': 'Los Más Vendidos',
    'home.bestsellersDesc': 'Nuestras fragancias más populares',
    'home.viewAll': 'Ver Todo',
    'home.bundles': 'Packs de Fragancias',
    'home.bundlesDesc': 'Ahorra más con packs seleccionados',
    'home.faq': 'Preguntas Frecuentes',
    'home.faqDesc': 'Todo lo que necesitas saber',
    'home.shopByBrand': 'Comprar por Marca',
    'faq.q1': '¿Qué estoy comprando?',
    'faq.a1': 'Estás comprando acceso a enlaces exclusivos de vendedores verificados.',
    'faq.q2': '¿Cómo recibo mi compra?',
    'faq.a2': 'Después de completar tu pedido, recibirás tu compra por correo electrónico al instante.',
    'faq.q3': '¿Cuál es su política de reembolso?',
    'faq.a3': 'Debido a la naturaleza digital de nuestros productos, todas las ventas son definitivas.',
    'faq.q4': '¿Qué tipo de fragancias venden?',
    'faq.a4': 'Ofrecemos fragancias 1:1 de alta calidad de vendedores de confianza. No son productos originales de marca.',
    'faq.q5': '¿Cómo contacto a los vendedores?',
    'faq.a5': 'Después de la compra, recibirás el enlace del vendedor por correo electrónico con toda la información de contacto.',
    'shop.title': 'Tienda',
    'shop.menCollection': 'Colección Hombre',
    'shop.womenCollection': 'Colección Mujer',
    'shop.allProducts': 'Todos los Productos',
    'shop.searchPlaceholder': 'Buscar fragancias...',
    'shop.sortBy': 'Ordenar por',
    'shop.featured': 'Destacados',
    'shop.priceLowHigh': 'Precio: Menor a Mayor',
    'shop.priceHighLow': 'Precio: Mayor a Menor',
    'shop.newest': 'Más Recientes',
    'shop.filters': 'Filtros',
    'shop.priceRange': 'Rango de Precio',
    'shop.brands': 'Marcas',
    'shop.noProducts': 'No se encontraron productos',
    'shop.clearFilters': 'Limpiar filtros',
    'shop.products': 'productos',
    'product.addToCart': 'Añadir al Carrito',
    'product.viewDetails': 'Ver Detalles',
    'product.off': 'DESCUENTO',
    'product.from': 'Desde',
    'checkout.title': 'Pago',
    'checkout.subtitle': 'Completa tu compra',
    'checkout.yourInfo': 'Tu Información',
    'checkout.email': 'CORREO ELECTRÓNICO',
    'checkout.emailPlaceholder': 'tu@email.com',
    'checkout.emailHelper': 'Asegúrate de que tu correo sea correcto para recibir el email de confirmación.',
    'checkout.firstName': 'NOMBRE',
    'checkout.lastName': 'APELLIDO',
    'checkout.country': 'PAÍS',
    'checkout.selectCountry': 'Seleccionar país...',
    'checkout.searchCountry': 'Buscar país...',
    'checkout.noCountry': 'País no encontrado.',
    'checkout.city': 'CIUDAD',
    'checkout.postalCode': 'CÓDIGO POSTAL',
    'checkout.streetAddress': 'DIRECCIÓN',
    'checkout.discountCode': 'CÓDIGO DE DESCUENTO',
    'checkout.applyDiscount': 'Aplicar',
    'checkout.discountApplied': 'aplicado',
    'checkout.orderSummary': 'Resumen del Pedido',
    'checkout.subtotal': 'Subtotal',
    'checkout.discount': 'Descuento',
    'checkout.total': 'Total',
    'checkout.payment': 'Pago',
    'checkout.payWithCard': 'Pagar con Tarjeta/Apple Pay',
    'checkout.payWithGiftCard': 'Pagar con tarjeta regalo',
    'checkout.giftCardOther': 'Si los otros métodos de pago no te funcionan',
    'checkout.giftCardCode': 'CÓDIGO DE TARJETA REGALO',
    'checkout.giftCardPlaceholder': 'Ingresa tu código de tarjeta regalo',
    'checkout.confirmPayment': 'Confirmar Pago',
    'checkout.confirmOrder': 'He Pagado — Confirmar Pedido',
    'checkout.processing': 'Procesando...',
    'checkout.emptyCart': 'Tu carrito está vacío',
    'checkout.emptyCartDesc': 'Añade artículos a tu carrito para proceder al pago.',
    'checkout.continueShopping': 'Seguir Comprando',
    'checkout.fillFields': 'Por favor completa todos los campos',
    'checkout.fillFieldsDesc': 'Completa tu información antes de pagar.',
    'checkout.revolutPopupTitle': 'Instrucciones de Pago Importantes',
    'checkout.revolutPopupText1': 'Debes ingresar exactamente',
    'checkout.revolutPopupText2': 'en el enlace de pago. Los pedidos con montos incorrectos',
    'checkout.revolutPopupText3': 'no',
    'checkout.revolutPopupText4': 'serán aceptados.',
    'checkout.revolutPopupText5': 'Después de completar tu pago, regresa a esta ventana para confirmar tu pago.',
    'checkout.revolutPopupCancel': 'Cancelar',
    'checkout.revolutPopupAccept': 'Entendido, Ir al Pago',
    'checkout.confirmTitle': 'Confirmación de Pago',
    'checkout.confirmWarning': 'Los pedidos sin pago serán rechazados en la revisión.',
    'checkout.confirmText': 'Tu pedido será revisado antes de enviar un correo de confirmación. Si el pago no se ha completado, tu pedido será rechazado. ¿Estás seguro de que has pagado?',
    'checkout.confirmGoBack': 'Volver',
    'checkout.confirmYes': 'Sí, He Pagado',
    'checkout.rejectedWarning': 'Los pedidos sin pago serán rechazados en la revisión.',
    'checkout.giftCardPopupTitle': 'Pago con Tarjeta Regalo',
    'checkout.giftCardPopupText': 'Si las otras opciones de pago no te funcionan, compra una tarjeta regalo en este enlace por el monto más cercano a tu pedido. Luego regresa al sitio e ingresa el código. Haz clic en confirmar pago.',
    'checkout.giftCardPopupCancel': 'Cancelar',
    'checkout.giftCardPopupAccept': 'Ir al Sitio de Tarjetas Regalo',
    'checkout.giftCardConfirmTitle': 'Confirmar Pago con Tarjeta Regalo',
    'checkout.giftCardConfirmText': '¿Estás seguro de que quieres enviar este código de tarjeta regalo? Tu pedido será revisado y recibirás un correo de confirmación una vez verificado el código.',
    'checkout.giftCardConfirmGoBack': 'Volver',
    'checkout.giftCardConfirmYes': 'Enviar Código de Tarjeta Regalo',
    'checkout.thankYou': '¡Gracias!',
    'checkout.thankYouPaypal': 'Tu compra está completa. Recibirás un correo con los detalles de tu pedido.',
    'checkout.thankYouRevolut': 'Tu pedido ha sido recibido. Recibirás el correo de confirmación tan pronto como se verifique el pago.',
    'checkout.thankYouGiftCard': 'Tu pedido ha sido recibido. Recibirás el correo de confirmación tan pronto como se verifique el código.',
    'checkout.thankYouSpam': 'Revisa tu carpeta de spam si no ves el correo en unos minutos.',
    'checkout.thankYouPatience': 'Esto suele tomar un momento. Gracias por tu paciencia.',
    'footer.description': 'Descubre enlaces exclusivos de vendedores de fragancias. Calidad premium, entrega digital instantánea.',
    'footer.shop': 'Tienda',
    'footer.menCollection': 'Colección Hombre',
    'footer.womenCollection': 'Colección Mujer',
    'footer.allProducts': 'Todos los Productos',
    'footer.support': 'Soporte',
    'footer.contactUs': 'Contáctanos',
    'footer.privacyPolicy': 'Privacidad',
    'footer.termsOfService': 'Términos',
    'footer.faq': 'FAQ',
    'footer.rights': 'Todos los derechos reservados.',
    'contact.title': 'Contáctanos',
    'contact.subtitle': 'Nos encantaría saber de ti',
    'productDetail.scentNotes': 'Notas Olfativas',
    'productDetail.reviews': 'Reseñas',
    'productDetail.delivery': 'Entrega',
    'cart.title': 'Tu Carrito',
    'cart.empty': 'Tu carrito está vacío',
    'cart.checkout': 'Pagar',
    'cart.remove': 'Eliminar',
    'auth.login': 'Iniciar Sesión',
    'auth.signup': 'Registrarse',
    'auth.logout': 'Cerrar Sesión',
    'general.poweredBy': 'Powered by Revolut',
    'general.secure': 'Seguro',
    'general.or': 'o',
    'general.information': 'Información',
    'general.confirmation': 'Confirmación',
    'general.step': 'Paso',
  },

  IT: {
    'nav.men': 'UOMO',
    'nav.women': 'DONNA',
    'nav.shopAll': 'TUTTO',
    'nav.contact': 'CONTATTO',
    'nav.account': 'ACCOUNT',
    'nav.myAccount': 'IL MIO ACCOUNT',
    'hero.subtitle': 'Fragranze Premium',
    'hero.shopNow': 'Acquista Ora',
    'hero.instantDelivery': 'Consegna Istantanea',
    'hero.verifiedSellers': 'Venditori Verificati',
    'hero.premiumQuality': 'Qualità Premium',
    'home.bestsellers': 'Più Venduti',
    'home.bestsellersDesc': 'Le nostre fragranze più amate',
    'home.viewAll': 'Vedi Tutto',
    'home.bundles': 'Pacchetti Fragranze',
    'home.bundlesDesc': 'Risparmia di più con pacchetti curati',
    'home.faq': 'Domande Frequenti',
    'home.faqDesc': 'Tutto quello che devi sapere',
    'home.shopByBrand': 'Per Marca',
    'faq.q1': 'Cosa sto comprando?',
    'faq.a1': "Stai acquistando l'accesso a link esclusivi di venditori verificati.",
    'faq.q2': 'Come ricevo il mio acquisto?',
    'faq.a2': "Dopo aver completato l'ordine, riceverai il tuo acquisto via email istantaneamente.",
    'faq.q3': 'Qual è la vostra politica di rimborso?',
    'faq.a3': 'A causa della natura digitale dei nostri prodotti, tutte le vendite sono definitive.',
    'faq.q4': 'Che tipo di fragranze vendete?',
    'faq.a4': 'Offriamo fragranze 1:1 di alta qualità da venditori fidati. Non sono prodotti di marca originali.',
    'faq.q5': 'Come contatto i venditori?',
    'faq.a5': "Dopo l'acquisto, riceverai il link del venditore via email con tutte le informazioni di contatto.",
    'shop.title': 'Negozio',
    'shop.menCollection': 'Collezione Uomo',
    'shop.womenCollection': 'Collezione Donna',
    'shop.allProducts': 'Tutti i Prodotti',
    'shop.searchPlaceholder': 'Cerca fragranze...',
    'shop.sortBy': 'Ordina per',
    'shop.featured': 'In Evidenza',
    'shop.priceLowHigh': 'Prezzo: Dal Basso',
    'shop.priceHighLow': "Prezzo: Dall'Alto",
    'shop.newest': 'Più Recenti',
    'shop.filters': 'Filtri',
    'shop.priceRange': 'Fascia di Prezzo',
    'shop.brands': 'Marchi',
    'shop.noProducts': 'Nessun prodotto trovato',
    'shop.clearFilters': 'Cancella filtri',
    'shop.products': 'prodotti',
    'product.addToCart': 'Aggiungi al Carrello',
    'product.viewDetails': 'Vedi Dettagli',
    'product.off': 'SCONTO',
    'product.from': 'Da',
    'checkout.title': 'Pagamento',
    'checkout.subtitle': 'Completa il tuo acquisto',
    'checkout.yourInfo': 'Le Tue Informazioni',
    'checkout.email': 'INDIRIZZO EMAIL',
    'checkout.emailPlaceholder': 'tua@email.com',
    'checkout.emailHelper': "Assicurati che la tua email sia corretta per ricevere l'email di conferma.",
    'checkout.firstName': 'NOME',
    'checkout.lastName': 'COGNOME',
    'checkout.country': 'PAESE',
    'checkout.selectCountry': 'Seleziona paese...',
    'checkout.searchCountry': 'Cerca paese...',
    'checkout.noCountry': 'Nessun paese trovato.',
    'checkout.city': 'CITTÀ',
    'checkout.postalCode': 'CODICE POSTALE',
    'checkout.streetAddress': 'INDIRIZZO',
    'checkout.discountCode': 'CODICE SCONTO',
    'checkout.applyDiscount': 'Applica',
    'checkout.discountApplied': 'applicato',
    'checkout.orderSummary': "Riepilogo dell'Ordine",
    'checkout.subtotal': 'Subtotale',
    'checkout.discount': 'Sconto',
    'checkout.total': 'Totale',
    'checkout.payment': 'Pagamento',
    'checkout.payWithCard': 'Paga con Carta/Apple Pay',
    'checkout.payWithGiftCard': 'Paga con carta regalo',
    'checkout.giftCardOther': 'Se gli altri metodi di pagamento non funzionano',
    'checkout.giftCardCode': 'CODICE CARTA REGALO',
    'checkout.giftCardPlaceholder': 'Inserisci il codice carta regalo',
    'checkout.confirmPayment': 'Conferma Pagamento',
    'checkout.confirmOrder': "Ho Pagato — Conferma Ordine",
    'checkout.processing': 'Elaborazione...',
    'checkout.emptyCart': 'Il tuo carrello è vuoto',
    'checkout.emptyCartDesc': 'Aggiungi articoli al carrello per procedere al pagamento.',
    'checkout.continueShopping': 'Continua lo Shopping',
    'checkout.fillFields': 'Compila tutti i campi',
    'checkout.fillFieldsDesc': 'Completa le tue informazioni prima di pagare.',
    'checkout.revolutPopupTitle': 'Istruzioni di Pagamento Importanti',
    'checkout.revolutPopupText1': 'Devi inserire esattamente',
    'checkout.revolutPopupText2': 'nel link di pagamento. Gli ordini con importi errati',
    'checkout.revolutPopupText3': 'non',
    'checkout.revolutPopupText4': 'saranno accettati.',
    'checkout.revolutPopupText5': 'Dopo aver completato il pagamento, torna a questa finestra per confermare il pagamento.',
    'checkout.revolutPopupCancel': 'Annulla',
    'checkout.revolutPopupAccept': 'Ho Capito, Procedi al Pagamento',
    'checkout.confirmTitle': 'Conferma Pagamento',
    'checkout.confirmWarning': 'Gli ordini senza pagamento verranno rifiutati alla verifica.',
    'checkout.confirmText': "Il tuo ordine verrà esaminato prima dell'invio dell'email di conferma. Se il pagamento non è stato completato, il tuo ordine verrà rifiutato. Sei sicuro di aver pagato?",
    'checkout.confirmGoBack': 'Indietro',
    'checkout.confirmYes': 'Sì, Ho Pagato',
    'checkout.rejectedWarning': 'Gli ordini senza pagamento verranno rifiutati alla verifica.',
    'checkout.giftCardPopupTitle': 'Pagamento con Carta Regalo',
    'checkout.giftCardPopupText': "Se le altre opzioni di pagamento non funzionano, acquista una carta regalo tramite questo link per l'importo più vicino al tuo ordine. Poi torna al sito e inserisci il codice. Clicca su conferma pagamento.",
    'checkout.giftCardPopupCancel': 'Annulla',
    'checkout.giftCardPopupAccept': 'Vai al Sito Carte Regalo',
    'checkout.giftCardConfirmTitle': 'Conferma Pagamento Carta Regalo',
    'checkout.giftCardConfirmText': "Sei sicuro di voler inviare questo codice carta regalo? Il tuo ordine verrà esaminato e riceverai un'email di conferma una volta verificato il codice.",
    'checkout.giftCardConfirmGoBack': 'Indietro',
    'checkout.giftCardConfirmYes': 'Invia Codice Carta Regalo',
    'checkout.thankYou': 'Grazie!',
    'checkout.thankYouPaypal': "Il tuo acquisto è completo. Riceverai un'email con i dettagli dell'ordine.",
    'checkout.thankYouRevolut': "Il tuo ordine è stato ricevuto. Riceverai l'email di conferma non appena il pagamento sarà verificato.",
    'checkout.thankYouGiftCard': "Il tuo ordine è stato ricevuto. Riceverai l'email di conferma non appena il codice sarà verificato.",
    'checkout.thankYouSpam': "Controlla la cartella spam se non ricevi l'email entro pochi minuti.",
    'checkout.thankYouPatience': 'Di solito ci vuole poco tempo. Grazie per la pazienza.',
    'footer.description': 'Scopri link esclusivi di venditori di fragranze. Qualità premium, consegna digitale istantanea.',
    'footer.shop': 'Negozio',
    'footer.menCollection': 'Collezione Uomo',
    'footer.womenCollection': 'Collezione Donna',
    'footer.allProducts': 'Tutti i Prodotti',
    'footer.support': 'Supporto',
    'footer.contactUs': 'Contattaci',
    'footer.privacyPolicy': 'Privacy',
    'footer.termsOfService': 'Termini',
    'footer.faq': 'FAQ',
    'footer.rights': 'Tutti i diritti riservati.',
    'contact.title': 'Contattaci',
    'contact.subtitle': 'Ci farebbe piacere sentirti',
    'productDetail.scentNotes': 'Note Olfattive',
    'productDetail.reviews': 'Recensioni',
    'productDetail.delivery': 'Consegna',
    'cart.title': 'Il Tuo Carrello',
    'cart.empty': 'Il tuo carrello è vuoto',
    'cart.checkout': 'Paga',
    'cart.remove': 'Rimuovi',
    'auth.login': 'Accedi',
    'auth.signup': 'Registrati',
    'auth.logout': 'Esci',
    'general.poweredBy': 'Powered by Revolut',
    'general.secure': 'Sicuro',
    'general.or': 'o',
    'general.information': 'Informazione',
    'general.confirmation': 'Conferma',
    'general.step': 'Passo',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

function detectBrowserLanguage(): Language {
  const browserLang = navigator.language?.substring(0, 2).toUpperCase();
  const supported: Language[] = ['EN', 'NL', 'DE', 'FR', 'ES', 'IT'];
  if (supported.includes(browserLang as Language)) return browserLang as Language;
  return 'EN';
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('preferred-language');
    if (saved && ['EN', 'NL', 'DE', 'FR', 'ES', 'IT'].includes(saved)) return saved as Language;
    return detectBrowserLanguage();
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('preferred-language', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['EN']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
