ALTER TABLE public.admin_live_counter
  ADD COLUMN IF NOT EXISTS gross NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS net NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS order_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS contributing_orders JSONB NOT NULL DEFAULT '[]'::jsonb;